export const messages = {
  'pt-BR': {
    common: { email: 'E-mail', password: 'Senha', signIn: 'Entrar', signOut: 'Sair', save: 'Salvar', cancel: 'Cancelar', loading: 'Carregando…', language: 'Idioma', portuguese: 'Português (Brasil)', english: 'English', currentUser: 'usuário atual' },
    auth: {
      createAccount: 'Criar conta', createAccountTitle: 'Crie sua conta', createAccountSubtitle: 'Comece com acesso seguro por e-mail e senha.', signInSubtitle: 'Acesse sua conta Zunera com segurança.',
      fullName: 'Nome completo', nameRequired: 'Informe seu nome completo.', nameShort: 'Use pelo menos 2 caracteres.',
      emailRequired: 'Informe seu e-mail.', emailInvalid: 'Informe um e-mail válido.', passwordRequired: 'Informe uma senha.', newPasswordRequired: 'Informe uma nova senha.', passwordMin: 'Use pelo menos 15 caracteres.', confirmPassword: 'Confirme a senha', confirmNewPassword: 'Confirme a nova senha', passwordsMatch: 'As senhas devem coincidir.',
      passwordHelp: 'Use de 15 a 64 caracteres. Espaços são permitidos. Evite senhas comuns ou comprometidas.', safetyUnavailable: 'A segurança da senha está temporariamente indisponível. Tente novamente em instantes.',
      alreadyHaveAccount: 'Já tem uma conta?', forgotPassword: 'Esqueceu sua senha?', accountOptions: 'Opções da conta', recoverPassword: 'Recuperar senha', recoverSubtitle: 'Receba um link de recuperação seguro sem expor o status da conta.', sendRecovery: 'Enviar instruções de recuperação', checkEmail: 'Verifique seu e-mail', recoverySent: 'Se existir uma conta para este e-mail, as instruções chegarão em breve.', returnToSignIn: 'Voltar para entrar',
      resetPassword: 'Redefinir senha', resetSubtitle: 'Use o link de recuperação mais recente e escolha uma nova senha.', recoveryToken: 'Token de recuperação', recoveryTokenRequired: 'O token de recuperação é obrigatório.', recoveryExpired: 'Link de recuperação expirado', recoveryExpiredDescription: 'Solicite um novo link de recuperação para redefinir sua senha.', recoveryInvalid: 'Link de recuperação inválido', recoveryInvalidDescription: 'Use o e-mail de recuperação mais recente ou solicite um novo link.', signInNow: 'Entrar agora',
      sessionEnding: 'Sessão terminando em breve', sessionExpiresIn: 'Sua sessão expirará em {seconds} segundos.', continueSession: 'Continuar sessão', sessionExpired: 'Sua sessão expirou. Entre novamente para continuar.', tooManyAttempts: 'Muitas tentativas de entrada. A recuperação continua disponível.', invalidCredentials: 'E-mail ou senha incorretos.', privacy: 'Ao continuar, você concorda com o tratamento de privacidade da Zunera.', privacyNotice: 'Aviso de privacidade', privacyRights: 'Direitos de privacidade',
    },
    app: { openNavigation: 'Abrir navegação', navigation: 'Navegação', primaryNavigation: 'Navegação principal', home: 'Início', financialAccounts: 'Contas financeiras', archivedAccounts: 'Contas arquivadas', categories: 'Categorias', archivedCategories: 'Categorias arquivadas', transactions: 'Transações', removedTransactions: 'Transações removidas', workspace: 'Espaço de trabalho', personal: 'Pessoal', accountMenu: 'Menu da conta de {name}', accountReady: 'Conta pronta', signedInAs: 'Conectado como {name}.', openAccounts: 'Abrir contas financeiras', idleExpires: 'Expiração por inatividade', absoluteExpires: 'Expiração absoluta', skipToContent: 'Pular para o conteúdo principal' },
    financialAccounts: { title: 'Contas financeiras', description: 'Crie e gerencie as contas onde seu dinheiro fica.', new: 'Nova conta', archived: 'Arquivadas', active: 'Contas ativas', created: 'Conta financeira criada.', saved: 'Detalhes da conta salvos.', archivedSuccess: 'Conta financeira arquivada.', restored: 'Conta financeira restaurada.', newDialog: 'Nova conta', editDialog: 'Editar conta', accountName: 'Nome da conta', accountType: 'Tipo de conta', openingBalance: 'Saldo inicial', balanceLocked: 'O saldo inicial está bloqueado porque esta conta já possui movimentações financeiras.', balanceHelp: 'Informe o saldo com que a conta iniciou, não uma receita.', institution: 'Instituição financeira (opcional)', color: 'Cor', icon: 'Ícone', saveChanges: 'Salvar alterações', create: 'Criar conta', activeSummary: 'Resumo das contas ativas', activeCount: '{count} conta(s) ativa(s)', nameRequired: 'Informe o nome da conta.', nameLength: 'O nome deve ter entre 1 e 120 caracteres.', typeRequired: 'Escolha um tipo de conta.', empty: 'Nenhuma conta ativa ainda. Crie sua primeira conta para começar.', emptyArchived: 'Ainda não há contas arquivadas.', archive: 'Arquivar', restore: 'Restaurar', archiveTitle: 'Arquivar conta', restoreTitle: 'Restaurar conta', archiveDescription: 'Arquivar “{name}”? Ela será removida das opções de contas ativas e do saldo ativo.', restoreDescription: 'Restaurar “{name}”? Ela ficará ativa novamente.', archivedTitle: 'Contas arquivadas', archivedDescription: 'As contas históricas ficam disponíveis aqui até você restaurá-las.', accountTypes: { checking: 'Conta corrente', savings: 'Conta poupança', cash_wallet: 'Dinheiro ou carteira', investment: 'Conta de investimento', digital: 'Conta digital', other: 'Outro' }, colors: { teal: 'Verde-azulado', blue: 'Azul', violet: 'Violeta', amber: 'Âmbar', rose: 'Rosa', cyan: 'Ciano' }, icons: { bank: 'Banco', piggy_bank: 'Cofrinho', wallet: 'Carteira', chart: 'Gráfico', smartphone: 'Celular', circle: 'Círculo' } },
    categories: { title: 'Categorias', description: 'Organize receitas e despesas com categorias padrão e suas próprias categorias.', new: 'Nova categoria', archived: 'Arquivadas', active: 'Categorias ativas', created: 'Categoria criada.', saved: 'Categoria atualizada.', archivedSuccess: 'Categoria arquivada.', restored: 'Categoria restaurada.', newDialog: 'Nova categoria', editDialog: 'Editar categoria', name: 'Nome da categoria', classification: 'Classificação financeira', classificationLocked: 'A classificação está bloqueada porque esta categoria possui histórico financeiro.', color: 'Cor (opcional)', icon: 'Ícone (opcional)', saveChanges: 'Salvar alterações', create: 'Criar categoria', nameRequired: 'Informe o nome da categoria.', nameLength: 'O nome deve ter entre 1 e 120 caracteres.', classificationRequired: 'Escolha receita ou despesa.', all: 'Todas', expense: 'Despesa', income: 'Receita', empty: 'Nenhuma categoria{type} ainda. Crie uma para começar.', emptyArchived: 'Ainda não há categorias{type} arquivadas.', systemDefault: 'Padrão do sistema', archivedTag: 'Arquivada', edit: 'Editar', archive: 'Arquivar', restore: 'Restaurar', editLabel: 'Editar categoria', archiveTitle: 'Arquivar categoria', restoreTitle: 'Restaurar categoria', archiveDescription: 'Arquivar “{name}”? Ela não aparecerá para novas transações, mas o histórico será mantido.', restoreDescription: 'Restaurar “{name}”? Ela voltará a ficar disponível para novas transações.', archivedTitle: 'Categorias arquivadas', archivedDescription: 'Categorias arquivadas ficam disponíveis para relatórios históricos e podem ser restauradas.', classifications: { income: 'Receita', expense: 'Despesa' }, colors: { teal: 'Verde-azulado', blue: 'Azul', violet: 'Violeta', amber: 'Âmbar', rose: 'Rosa', cyan: 'Ciano' }, icons: { home: 'Casa', utensils: 'Alimentação', car: 'Carro', heart: 'Saúde', book: 'Educação', gamepad: 'Entretenimento', shopping_bag: 'Compras', receipt: 'Contas', landmark: 'Impostos', circle: 'Outro', wallet: 'Carteira', briefcase: 'Serviços', chart: 'Investimentos', gift: 'Presentes', refund: 'Reembolsos' } },
  },
  en: {
    common: { email: 'Email', password: 'Password', signIn: 'Sign in', signOut: 'Sign out', save: 'Save', cancel: 'Cancel', loading: 'Loading…', language: 'Language', portuguese: 'Português (Brasil)', english: 'English', currentUser: 'current user' },
    auth: {
      createAccount: 'Create account', createAccountTitle: 'Create your account', createAccountSubtitle: 'Start with secure email and password access.', signInSubtitle: 'Access your Zunera account securely.',
      fullName: 'Full name', nameRequired: 'Enter your full name.', nameShort: 'Use at least 2 characters.', emailRequired: 'Enter your email.', emailInvalid: 'Enter a valid email.', passwordRequired: 'Enter a password.', newPasswordRequired: 'Enter a new password.', passwordMin: 'Use at least 15 characters.', confirmPassword: 'Confirm password', confirmNewPassword: 'Confirm new password', passwordsMatch: 'Passwords must match.',
      passwordHelp: 'Use 15 to 64 characters. Spaces are allowed. Avoid common or compromised passwords.', safetyUnavailable: 'Password safety is temporarily unavailable. Try again soon.', alreadyHaveAccount: 'Already have an account?', forgotPassword: 'Forgot password?', accountOptions: 'Account options', recoverPassword: 'Recover password', recoverSubtitle: 'Get a secure recovery link without exposing account status.', sendRecovery: 'Send recovery instructions', checkEmail: 'Check your email', recoverySent: 'If an account exists for that email, recovery instructions will arrive shortly.', returnToSignIn: 'Return to sign in',
      resetPassword: 'Reset password', resetSubtitle: 'Use the newest recovery link and choose a new password.', recoveryToken: 'Recovery token', recoveryTokenRequired: 'Recovery token is required.', recoveryExpired: 'Recovery link expired', recoveryExpiredDescription: 'Request a new recovery link to reset your password.', recoveryInvalid: 'Recovery link invalid', recoveryInvalidDescription: 'Use the newest recovery email or request a new link.', signInNow: 'Sign in now', sessionEnding: 'Session ending soon', sessionExpiresIn: 'Your session will expire in {seconds} seconds.', continueSession: 'Continue session', sessionExpired: 'Your session expired. Sign in again to continue.', tooManyAttempts: 'Too many sign-in attempts. Recovery remains available.', invalidCredentials: 'Email or password is incorrect.', privacy: 'By continuing, you agree to Zunera privacy handling.', privacyNotice: 'Privacy notice', privacyRights: 'Privacy rights',
    },
    app: { openNavigation: 'Open navigation', navigation: 'Navigation', primaryNavigation: 'Primary navigation', home: 'Home', financialAccounts: 'Financial accounts', archivedAccounts: 'Archived accounts', categories: 'Categories', archivedCategories: 'Archived categories', transactions: 'Transactions', removedTransactions: 'Removed transactions', workspace: 'Workspace', personal: 'Personal', accountMenu: 'Account menu for {name}', accountReady: 'Account ready', signedInAs: 'Signed in as {name}.', openAccounts: 'Open financial accounts', idleExpires: 'Idle expires', absoluteExpires: 'Absolute expires', skipToContent: 'Skip to main content' },
    financialAccounts: { title: 'Financial accounts', description: 'Create and manage the accounts where your money is held.', new: 'New account', archived: 'Archived', active: 'Active accounts', created: 'Financial account created.', saved: 'Account details saved.', archivedSuccess: 'Financial account archived.', restored: 'Financial account restored.', newDialog: 'New account', editDialog: 'Edit account', accountName: 'Account name', accountType: 'Account type', openingBalance: 'Opening balance', balanceLocked: 'The opening balance is locked because this account already has financial movements.', balanceHelp: 'Enter the balance the account started with, not income.', institution: 'Financial institution (optional)', color: 'Color', icon: 'Icon', saveChanges: 'Save changes', create: 'Create account', activeSummary: 'Active account summary', activeCount: '{count} active account(s)', nameRequired: 'Enter an account name.', nameLength: 'Account name must be between 1 and 120 characters.', typeRequired: 'Choose an account type.', empty: 'No active accounts yet. Create your first account to get started.', emptyArchived: 'No archived accounts yet.', archive: 'Archive', restore: 'Restore', archiveTitle: 'Archive account', restoreTitle: 'Restore account', archiveDescription: 'Archive “{name}”? It will be removed from active account choices and the active balance.', restoreDescription: 'Restore “{name}”? It will become active again.', archivedTitle: 'Archived accounts', archivedDescription: 'Historical accounts stay available here until you restore them.', accountTypes: { checking: 'Checking account', savings: 'Savings account', cash_wallet: 'Cash or wallet', investment: 'Investment account', digital: 'Digital account', other: 'Other' }, colors: { teal: 'Teal', blue: 'Blue', violet: 'Violet', amber: 'Amber', rose: 'Rose', cyan: 'Cyan' }, icons: { bank: 'Bank', piggy_bank: 'Piggy bank', wallet: 'Wallet', chart: 'Chart', smartphone: 'Mobile phone', circle: 'Circle' } },
    categories: { title: 'Categories', description: 'Organize income and expenses with system defaults and your own categories.', new: 'New category', archived: 'Archived', active: 'Active categories', created: 'Category created.', saved: 'Category updated.', archivedSuccess: 'Category archived.', restored: 'Category restored.', newDialog: 'New category', editDialog: 'Edit category', name: 'Category name', classification: 'Financial classification', classificationLocked: 'Classification is locked because this category has financial history.', color: 'Color (optional)', icon: 'Icon (optional)', saveChanges: 'Save changes', create: 'Create category', nameRequired: 'Enter a category name.', nameLength: 'Category name must be between 1 and 120 characters.', classificationRequired: 'Choose income or expense.', all: 'All', expense: 'Expense', income: 'Income', empty: 'No {type}categories yet. Create one to get started.', emptyArchived: 'No archived {type}categories yet.', systemDefault: 'System default', archivedTag: 'Archived', edit: 'Edit', archive: 'Archive', restore: 'Restore', editLabel: 'Edit category', archiveTitle: 'Archive category', restoreTitle: 'Restore category', archiveDescription: 'Archive “{name}”? It will no longer appear for new transactions, while past history stays intact.', restoreDescription: 'Restore “{name}”? It will become available for new transactions again.', archivedTitle: 'Archived categories', archivedDescription: 'Archived categories remain available for historical reporting and can be restored.', classifications: { income: 'Income', expense: 'Expense' }, colors: { teal: 'Teal', blue: 'Blue', violet: 'Violet', amber: 'Amber', rose: 'Rose', cyan: 'Cyan' }, icons: { home: 'Home', utensils: 'Food', car: 'Car', heart: 'Health', book: 'Education', gamepad: 'Entertainment', shopping_bag: 'Shopping', receipt: 'Bills', landmark: 'Taxes', circle: 'Other', wallet: 'Wallet', briefcase: 'Services', chart: 'Investments', gift: 'Gifts', refund: 'Refunds' } },
  },
}
